<a href="https://colab.research.google.com/github/hexe007/lekcjaPT/blob/main/lekcjaPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

to jest test jak zmienic linijki kodu w linijki tekstowe- bardzo prosto--wystarczy kliknac i przytrzymac ctrl z drukrotnym nacisnieciem mm

In [ ]:
!nvidia-smi


/bin/bash: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


tensors

In [ ]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#shift + enter ---uruchomienie run ndim-non dimention

In [ ]:
scalar.item() #get tensor back as int

7

In [ ]:
#vector
vector=torch.tensor([7,7])

In [ ]:
vector.ndim #number of square cloasing brackets,numer zamknietych nawiasow

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])

In [ ]:
#matrix

In [ ]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [ ]:
#dim ([1,3,3]) 1-oznacza pierwszy nawias kwadratowy, 2-ilosc kolejnych rzedow,3-ilosc kolejnych kolumn


In [ ]:
TENSOR=torch.tensor([[[[[1,2,3],
                        [2,3,4],
                        [3,2,5],
                        [1,2,4],
                        [7,8,9],
                        [1,6,3]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [2, 3, 4],
           [3, 2, 5],
           [1, 2, 4],
           [7, 8, 9],
           [1, 6, 3]]]]])

In [ ]:
TENSOR.ndim

5

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 6, 3])

In [ ]:
TENSOR[0]

tensor([[[[1, 2, 3],
          [2, 3, 4],
          [3, 2, 5],
          [1, 2, 4],
          [7, 8, 9],
          [1, 6, 3]]]])

###RANDOM TENSORS

In [ ]:
#`START WITH RANDOM NUMERS--->LOOK AT THE DATA-->UPDATE RANDM NUMBERS--->LOOK AT DATA-->UPDATE RANDOM NUMBERS`

In [ ]:
#CREATE OF RANDOM TENSOR
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9591, 0.5503, 0.2733, 0.6132],
        [0.6198, 0.9342, 0.0064, 0.2627],
        [0.4151, 0.3666, 0.3711, 0.7708]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#crate a random tensor with similar shape to an image tensor

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))#hight with colour chanel R G B
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# zeros and ones

In [ ]:
#create a tensor of all zeroes
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
#RANGE OF TENSORS
torch.range(0,10)

<ipython-input-41-9d45fe218c47>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.__version__

'2.0.0+cu118'

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten=torch.arange(1,11)

In [ ]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten=torch.arange(start=0,end=1000,step=77)

In [ ]:
#one_to_ten

In [ ]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensors data types
 3 BIG PROBLEMS WITH TENSORS:
 1.TENSORS NOT RIGHT DATATYPE
 2.TENSORS NOT RIGHT SHAPE
 3.TENSORS NOT ON THE RIGHT DEVICE

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16 #zmiana dtypu z float 32 na float 16
                             device=None #what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

SyntaxError: ignored

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float32)# zmiana float 16 na float 32
float_16_tensor

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

In [ ]:
float_32_tensor*int_32_tensor

In [ ]:
float_16_tensor.dtype

###getting some info from tensors (tensors attributes)


1.    1.TENSORS NOT RIGHT DATATYPE -to get `dtypes`can use tensor.dtype
      2.TENSORS NOT RIGHT SHAPE - to get shape can use tensor.shape
     3.TENSORS NOT ON THE RIGHT DEVICE - to get device use tensor.device





In [ ]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

In [ ]:
#find out details about some tnesor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

In [ ]:
jakis_tensor=torch.rand(2,4,3)
jakis_tensor

In [ ]:
jakis_tensor.dtype

In [ ]:
jakis_tensor_nowy=jakis_tensor.type(torch.float64)
jakis_tensor_nowy

In [ ]:
print(f"data type tego:{jakis_tensor_nowy.dtype}")
print(f"ksztalt tego nowego{jakis_tensor_nowy.shape}")
print(f"na jakim device idzie {jakis_tensor_nowy.device}")

#MANIPUALTING TENSORS TENSORS OPERATIONS!

In [ ]:
###TENSORS operation include
#Addition
#Subctraction
#Multiplication(element-wise)
#Division
#Matrix multiplication

In [ ]:
#crate a tensor
tensor=torch.tensor([1,2,3])
tensor + 10

In [ ]:
tensor * 10

In [ ]:
tensor

In [ ]:
#tensor=tensor*10

In [ ]:
tensor

In [ ]:
tensor - 10

In [ ]:
tensor


In [ ]:
tensor

In [ ]:
torch.mul(tensor,10)

In [ ]:
torch.add(tensor,10)

In [ ]:
#MATRIX MULTIPLICATION 2 WAYS:
#ELEMENT-WISE MULTIPLICATION
#MATRIX MULTIPLICATION(dot product)

In [ ]:
print(tensor,"*", tensor) # zwykle mnozenie

In [ ]:
print(f"Equals:{tensor * tensor}")

In [ ]:
#teraz mnozenie prezz marix multiplication

In [ ]:
torch.matmul(tensor, tensor) #MATMUL metoda matematyczna pytorcha

In [ ]:
#matrix multiplication by hand
tensor

In [ ]:
 10 *10 + 20*20+ 30*30 

In [ ]:
%%time 
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

In [ ]:
%%time
torch.matmul(tensor,tensor)

In [ ]:
#SHAPE ERROR IN MATRIX MULTIPLICATION
#1. THE **INNER DIMENSIONS UST MATCH:
#(3,[2]) @ ([3],2) WONT WORK, ---> @ MNOZENIE, [2][3]--->inner dimensions,MUSZA BYC TAKIE SAME ZEBY ZADZIALALO!
#(2,[3]) @ ([3],2) WILL WORK --->[]MUSZA BYC TAKIE SAME
#(3,[2]) @ ([2],3) WILL WORK --->[]MUSZA BYC TAKIE SAME
#
#2.THE RESULTING MATRIX HAS THE SHAPE OF THE ** OUTER DIMENSIONS:
#(2,3) @ (3,2) --->(2,2)
#(3,2) @ (2,3) ---> (3,3)

In [ ]:
torch.rand(3,2).shape

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2)) #MM---> KROTSZA WERSJA OF MATMUL,SKROT MM

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

#Shapes for matrix multiplication

In [ ]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])



In [ ]:
tensor_A

In [ ]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B).SHAPE

In [ ]:
#torch.mm(tensor_A,tensor_B).shape

In [ ]:
tensor_A.shape, tensor_B.shape

TO FIX OUT TENSOR SHAPE ISSUES WE CAN MANIPULATE THE SHAPE OF ONE OF OUR TENSORS USING TRANSPOSE!!!

A TRANSPOSE SWITCHES THE AXES OR DIMENSIONS OF A GIVEN TENSOR

In [ ]:
tensor_B.T, tensor_B

In [ ]:
tensor_B

In [ ]:
tensor_B.T

In [ ]:
tensor_B.shape

In [ ]:
tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A,tensor_B.T).shape

In [ ]:
#The matrix multiplication operation works when tensor_B is transposed (T)
print(f"Original shapes: tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape} (SAME SHAPE AS ABOVE), tensor_B.T={tensor_B.T.shape}")
print(f"multiplying:{tensor_A.shape} @ {tensor_B.T.shape}<----- INNER DIMENSIONS MUST MUCH")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

#finding the min,max,mean,tensro aggregation

In [ ]:
#create a tensor
x =torch.arange(1,100,10)
x
x.dtype

torch.int64

In [ ]:
torch.min(x)

tensor(1)

In [ ]:
x.min()

tensor(1)

In [ ]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
torch.mean(x.type(torch.float32)) # the torch.mean() function requires a tensor of float32 datatype to work

tensor(46.)

In [ ]:
x.type(torch.float32).mean()

tensor(46.)

In [ ]:
torch.sum(x)


tensor(460)

In [ ]:
x.sum()

tensor(460)

#ARG MAX AND ARG MIN -POZYCJA MIN I MAX

In [ ]:
#FINDING THE POSITIONAL 
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax() #pozycja na indexie 9

tensor(9)

In [ ]:
x[9] #szukanie po indeksie

tensor(91)

#RESHAPING,STACKING,SQUEEZING AND UNSQUEZZING

*RESHAPING- RESHAPE AN INPUT TENSOR TO A DEFINED SHAPE
*VIEW-RETURN A VIEW OF AN INPUT TENSOR OF CERTAIN SHAPE BUT KEEP THE SAME MEMORY AS TH ORIGINAL TENSOR
*STACKING- COMBINE MULTIPLE TENSOR ON TOP OF EACH OTHER(VSTACK) ORSIDE BY SIDE(HSTACK),
*SQUEEZE-REMOVES ALL 1 DIMENSIONS FROM A TENSOR
*UNSQUEEZE- ADD A 1 DIMENSION TO A TERGET
*PERMUTE-RETURN A VIEW OF THE INPUT WITH DIMENSIONS PERMUTED

In [ ]:
import torch
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x(because the view of the tensor has the same memory as oryginal input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on top of each other 
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])