<a href="https://colab.research.google.com/github/hexe007/lekcjaPT/blob/main/lekcjaPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

to jest test jak zmienic linijki kodu w linijki tekstowe- bardzo prosto--wystarczy kliknac i przytrzymac ctrl z drukrotnym nacisnieciem mm

In [1]:
!nvidia-smi


/bin/bash: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


tensors

In [3]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#shift + enter ---uruchomienie run ndim-non dimention

In [6]:
scalar.item() #get tensor back as int

7

In [7]:
#vector
vector=torch.tensor([7,7])

In [8]:
vector.ndim #number of square cloasing brackets,numer zamknietych nawiasow

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])

In [11]:
#matrix

In [12]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [21]:
#dim ([1,3,3]) 1-oznacza pierwszy nawias kwadratowy, 2-ilosc kolejnych rzedow,3-ilosc kolejnych kolumn


In [22]:
TENSOR=torch.tensor([[[[[1,2,3],
                        [2,3,4],
                        [3,2,5],
                        [1,2,4],
                        [7,8,9],
                        [1,6,3]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [2, 3, 4],
           [3, 2, 5],
           [1, 2, 4],
           [7, 8, 9],
           [1, 6, 3]]]]])

In [23]:
TENSOR.ndim

5

In [24]:
TENSOR.shape

torch.Size([1, 1, 1, 6, 3])

In [25]:
TENSOR[0]

tensor([[[[1, 2, 3],
          [2, 3, 4],
          [3, 2, 5],
          [1, 2, 4],
          [7, 8, 9],
          [1, 6, 3]]]])

###RANDOM TENSORS

In [26]:
#`START WITH RANDOM NUMERS--->LOOK AT THE DATA-->UPDATE RANDM NUMBERS--->LOOK AT DATA-->UPDATE RANDOM NUMBERS`

In [27]:
#CREATE OF RANDOM TENSOR
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1860, 0.2389, 0.4600, 0.2966],
        [0.4952, 0.7684, 0.1209, 0.4046],
        [0.1899, 0.6861, 0.9362, 0.5122]])

In [28]:
random_tensor.ndim

2

In [29]:
#crate a random tensor with similar shape to an image tensor

In [30]:
random_image_size_tensor = torch.rand(size=(224,224,3))#hight with colour chanel R G B
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# zeros and ones

In [31]:
#create a tensor of all zeroes
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
#all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [35]:
random_tensor.dtype

torch.float32

In [36]:
#RANGE OF TENSORS
torch.range(0,10)

<ipython-input-36-9d45fe218c47>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
torch.__version__

'2.0.0+cu118'

In [38]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
one_to_ten=torch.arange(1,11)

In [40]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
one_to_ten=torch.arange(start=0,end=1000,step=77)

In [42]:
#one_to_ten

In [43]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensors data types
 3 BIG PROBLEMS WITH TENSORS:
 1.TENSORS NOT RIGHT DATATYPE
 2.TENSORS NOT RIGHT SHAPE
 3.TENSORS NOT ON THE RIGHT DEVICE

In [45]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16 #zmiana dtypu z float 32 na float 16
                             device=None #what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

SyntaxError: ignored

In [47]:
float_16_tensor=float_32_tensor.type(torch.float32)# zmiana float 16 na float 32
float_16_tensor

NameError: ignored

In [48]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [105]:
float_32_tensor*int_32_tensor

NameError: ignored

In [152]:
float_16_tensor.dtype

NameError: ignored

###getting some info from tensors (tensors attributes)


1.    1.TENSORS NOT RIGHT DATATYPE -to get `dtypes`can use tensor.dtype
      2.TENSORS NOT RIGHT SHAPE - to get shape can use tensor.shape
     3.TENSORS NOT ON THE RIGHT DEVICE - to get device use tensor.device





In [153]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.9199, 0.2917, 0.0911, 0.7330],
        [0.1728, 0.0486, 0.0885, 0.5365],
        [0.2908, 0.9132, 0.4769, 0.3754]])

In [154]:
#find out details about some tnesor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.9199, 0.2917, 0.0911, 0.7330],
        [0.1728, 0.0486, 0.0885, 0.5365],
        [0.2908, 0.9132, 0.4769, 0.3754]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


In [155]:
jakis_tensor=torch.rand(2,4,3)
jakis_tensor

tensor([[[0.3865, 0.8379, 0.7598],
         [0.9377, 0.0328, 0.6177],
         [0.2613, 0.1385, 0.9460],
         [0.4241, 0.4131, 0.2268]],

        [[0.4614, 0.8720, 0.8223],
         [0.7582, 0.6760, 0.1479],
         [0.8688, 0.7424, 0.8436],
         [0.0424, 0.6302, 0.1202]]])

In [156]:
jakis_tensor.dtype

torch.float32

In [157]:
jakis_tensor_nowy=jakis_tensor.type(torch.float64)
jakis_tensor_nowy

tensor([[[0.3865, 0.8379, 0.7598],
         [0.9377, 0.0328, 0.6177],
         [0.2613, 0.1385, 0.9460],
         [0.4241, 0.4131, 0.2268]],

        [[0.4614, 0.8720, 0.8223],
         [0.7582, 0.6760, 0.1479],
         [0.8688, 0.7424, 0.8436],
         [0.0424, 0.6302, 0.1202]]], dtype=torch.float64)

In [158]:
print(f"data type tego:{jakis_tensor_nowy.dtype}")
print(f"ksztalt tego nowego{jakis_tensor_nowy.shape}")
print(f"na jakim device idzie {jakis_tensor_nowy.device}")

data type tego:torch.float64
ksztalt tego nowegotorch.Size([2, 4, 3])
na jakim device idzie cpu


#MANIPUALTING TENSORS TENSORS OPERATIONS!

In [159]:
###TENSORS operation include
#Addition
#Subctraction
#Multiplication(element-wise)
#Division
#Matrix multiplication

In [160]:
#crate a tensor
tensor=torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [161]:
tensor * 10

tensor([10, 20, 30])

In [162]:
tensor

tensor([1, 2, 3])

In [163]:
#tensor=tensor*10

In [164]:
tensor

tensor([1, 2, 3])

In [165]:
tensor - 10

tensor([-9, -8, -7])

In [166]:
tensor


tensor([1, 2, 3])

In [167]:
tensor

tensor([1, 2, 3])

In [168]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [169]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [170]:
#MATRIX MULTIPLICATION 2 WAYS:
#ELEMENT-WISE MULTIPLICATION
#MATRIX MULTIPLICATION(dot product)

In [171]:
print(tensor,"*", tensor) # zwykle mnozenie

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [172]:
print(f"Equals:{tensor * tensor}")

Equals:tensor([1, 4, 9])


In [173]:
#teraz mnozenie prezz marix multiplication

In [174]:
torch.matmul(tensor, tensor) #MATMUL metoda matematyczna pytorcha

tensor(14)

In [175]:
#matrix multiplication by hand
tensor

tensor([1, 2, 3])

In [176]:
 10 *10 + 20*20+ 30*30 

1400

In [177]:
%%time 
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.71 ms, sys: 0 ns, total: 1.71 ms
Wall time: 2.33 ms


In [178]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.32 ms, sys: 38 µs, total: 1.36 ms
Wall time: 1.24 ms


tensor(14)

In [179]:
#SHAPE ERROR IN MATRIX MULTIPLICATION
#1. THE **INNER DIMENSIONS UST MATCH:
#(3,[2]) @ ([3],2) WONT WORK, ---> @ MNOZENIE, [2][3]--->inner dimensions,MUSZA BYC TAKIE SAME ZEBY ZADZIALALO!
#(2,[3]) @ ([3],2) WILL WORK --->[]MUSZA BYC TAKIE SAME
#(3,[2]) @ ([2],3) WILL WORK --->[]MUSZA BYC TAKIE SAME
#
#2.THE RESULTING MATRIX HAS THE SHAPE OF THE ** OUTER DIMENSIONS:
#(2,3) @ (3,2) --->(2,2)
#(3,2) @ (2,3) ---> (3,3)

In [180]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [181]:
torch.matmul(torch.rand(2,3), torch.rand(3,2)) #MM---> KROTSZA WERSJA OF MATMUL,SKROT MM

tensor([[0.4045, 0.4028],
        [0.4191, 0.5039]])

In [182]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

#Shapes for matrix multiplication

In [183]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])



In [184]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [185]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B).SHAPE

In [186]:
#torch.mm(tensor_A,tensor_B).shape

In [187]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

TO FIX OUT TENSOR SHAPE ISSUES WE CAN MANIPULATE THE SHAPE OF ONE OF OUR TENSORS USING TRANSPOSE!!!

A TRANSPOSE SWITCHES THE AXES OR DIMENSIONS OF A GIVEN TENSOR

In [188]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [189]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [190]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [191]:
tensor_B.shape

torch.Size([3, 2])

In [192]:
tensor_B.T.shape

torch.Size([2, 3])

In [193]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [194]:
#The matrix multiplication operation works when tensor_B is transposed (T)
print(f"Original shapes: tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape} (SAME SHAPE AS ABOVE), tensor_B.T={tensor_B.T.shape}")
print(f"multiplying:{tensor_A.shape} @ {tensor_B.T.shape}<----- INNER DIMENSIONS MUST MUCH")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2]) (SAME SHAPE AS ABOVE), tensor_B.T=torch.Size([2, 3])
multiplying:torch.Size([3, 2]) @ torch.Size([2, 3])<----- INNER DIMENSIONS MUST MUCH
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


#finding the min,max,mean,tensro aggregation

In [195]:
#create a tensor
x =torch.arange(1,100,10)
x
x.dtype

torch.int64

In [196]:
torch.min(x)

tensor(1)

In [197]:
x.min()

tensor(1)

In [198]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [199]:
torch.mean(x.type(torch.float32)) # the torch.mean() function requires a tensor of float32 datatype to work

tensor(46.)

In [200]:
x.type(torch.float32).mean()

tensor(46.)

In [201]:
torch.sum(x)


tensor(460)

In [202]:
x.sum()

tensor(460)

#ARG MAX AND ARG MIN -POZYCJA MIN I MAX

In [203]:
#FINDING THE POSITIONAL 
x.argmin()

tensor(0)

In [204]:
x[0]

tensor(1)

In [205]:
x.argmax() #pozycja na indexie 9

tensor(9)

In [206]:
x[9] #szukanie po indeksie

tensor(91)

#RESHAPING,STACKING,SQUEEZING AND UNSQUEZZING

*RESHAPING- RESHAPE AN INPUT TENSOR TO A DEFINED SHAPE
*VIEW-RETURN A VIEW OF AN INPUT TENSOR OF CERTAIN SHAPE BUT KEEP THE SAME MEMORY AS TH ORIGINAL TENSOR
*STACKING- COMBINE MULTIPLE TENSOR ON TOP OF EACH OTHER(VSTACK) ORSIDE BY SIDE(HSTACK),
*SQUEEZE-REMOVES ALL 1 DIMENSIONS FROM A TENSOR
*UNSQUEEZE- ADD A 1 DIMENSION TO A TERGET
*PERMUTE-RETURN A VIEW OF THE INPUT WITH DIMENSIONS PERMUTED

In [207]:
import torch
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [208]:
#add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [209]:
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [210]:
#change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [211]:
#changing z changes x(because the view of the tensor has the same memory as oryginal input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [212]:
#stack tensors on top of each other 
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [213]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [226]:
#squeeze-removes all single dim from tensor
print(f"Previous tensor:{x_reshaped}")
print(f"previous shape:{x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"New shape:{x_squeezed.shape}")



#x=torch.zeros(2,1,2,1,2)

Previous tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
previous shape:torch.Size([9, 1])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [230]:
#torch.unsqueeze()---> adds a single dim to a target tensor at specific dim
print(f"previous target:{x_squeezed}")
print(f"previous shape:{x_squeezed.shape}")

#add an extra dim with unsqueezed
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")




previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape:torch.Size([9])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape:torch.Size([1, 9])


In [231]:
#torch.permute()---> rearranges the dim of a target tensor in a specified order

x_original=torch.rand(size=(224,224,3)) #[height,width,colour_channels]

#Permute the original tensor to rearrange the axis(or dim) order 
x_permuted=x_original.permute(2,0,1) #shifts axis 0-->1, 1-->2, 2--->0

print(f"Previous shape:{x_original.shape}")
print(f"\nNew shape:{x_permuted.shape}") #[colour_channels,height,width]


Previous shape:torch.Size([224, 224, 3])

New shape:torch.Size([3, 224, 224])


In [215]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [217]:
y=torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [218]:
y=torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [219]:
y=torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [220]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [221]:
x_reshaped.shape

torch.Size([9, 1])

In [223]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [224]:
x_reshaped.squeeze().shape

torch.Size([9])

In [232]:
x_original[0,0,0]= 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

##Indexing (selecting data from tensor)

indexing with pytorch is similar with indexing with numpy

In [233]:
#creating a tensor

import torch
x=torch.arange(1,10).reshape(1,3,3)

x,x.shape




(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [234]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [235]:
#lets index on the middle beacket(dim=1)
x[0][0] # or x[0,0]

tensor([1, 2, 3])

In [236]:
x[0][0][0]

tensor(1)

In [237]:
x[0][0][1]

tensor(2)

In [238]:
x[0][1][1]


tensor(5)

In [239]:
x[0][1][0]

tensor(4)

In [240]:
#You can also use [:] to select all of a target dim
x[:,0]

tensor([[1, 2, 3]])

In [241]:
#get all values of zeroth and first dim,but only index one of second dim
x[:,:,1]

tensor([[2, 5, 8]])