<a href="https://colab.research.google.com/github/hexe007/lekcjaPT/blob/main/lekcjaPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

to jest test jak zmienic linijki kodu w linijki tekstowe- bardzo prosto--wystarczy kliknac i przytrzymac ctrl z drukrotnym nacisnieciem mm

In [108]:
!nvidia-smi


/bin/bash: nvidia-smi: command not found


In [109]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


tensors

In [110]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [111]:
scalar.ndim

0

In [112]:
#shift + enter ---uruchomienie run ndim-non dimention

In [113]:
scalar.item() #get tensor back as int

7

In [114]:
#vector
vector=torch.tensor([7,7])

In [115]:
vector.ndim #number of square cloasing brackets,numer zamknietych nawiasow

1

In [116]:
vector.shape

torch.Size([2])

In [117]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])

In [118]:
#matrix

In [119]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [120]:
MATRIX.ndim

2

In [121]:
MATRIX[0]

tensor([7, 8])

In [122]:
MATRIX[1]

tensor([ 9, 10])

In [123]:
MATRIX.shape

torch.Size([2, 2])

In [124]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [125]:
TENSOR.ndim

3

In [126]:
TENSOR.shape

torch.Size([1, 3, 3])

In [127]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [128]:
#dim ([1,3,3]) 1-oznacza pierwszy nawias kwadratowy, 2-ilosc kolejnych rzedow,3-ilosc kolejnych kolumn


In [129]:
TENSOR=torch.tensor([[[[[1,2,3],
                        [2,3,4],
                        [3,2,5],
                        [1,2,4],
                        [7,8,9],
                        [1,6,3]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [2, 3, 4],
           [3, 2, 5],
           [1, 2, 4],
           [7, 8, 9],
           [1, 6, 3]]]]])

In [130]:
TENSOR.ndim

5

In [131]:
TENSOR.shape

torch.Size([1, 1, 1, 6, 3])

In [132]:
TENSOR[0]

tensor([[[[1, 2, 3],
          [2, 3, 4],
          [3, 2, 5],
          [1, 2, 4],
          [7, 8, 9],
          [1, 6, 3]]]])

###RANDOM TENSORS

In [133]:
#`START WITH RANDOM NUMERS--->LOOK AT THE DATA-->UPDATE RANDM NUMBERS--->LOOK AT DATA-->UPDATE RANDOM NUMBERS`

In [134]:
#CREATE OF RANDOM TENSOR
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6707, 0.7725, 0.1685, 0.0495],
        [0.5916, 0.2232, 0.0351, 0.8302],
        [0.9872, 0.5239, 0.8760, 0.6612]])

In [135]:
random_tensor.ndim

2

In [136]:
#crate a random tensor with similar shape to an image tensor

In [138]:
random_image_size_tensor = torch.rand(size=(224,224,3))#hight with colour chanel R G B
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# zeros and ones

In [139]:
#create a tensor of all zeroes
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [141]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [143]:
#all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [144]:
ones.dtype

torch.float32

In [145]:
random_tensor.dtype

torch.float32

In [146]:
#RANGE OF TENSORS
torch.range(0,10)

<ipython-input-146-9d45fe218c47>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [147]:
torch.__version__

'2.0.0+cu118'

In [148]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
one_to_ten=torch.arange(1,11)

In [150]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [153]:
one_to_ten=torch.arange(start=0,end=1000,step=77)

In [154]:
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [155]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensors data types
 3 BIG PROBLEMS WITH TENSORS:
 1.TENSORS NOT RIGHT DATATYPE
 2.TENSORS NOT RIGHT SHAPE
 3.TENSORS NOT ON THE RIGHT DEVICE

In [156]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16 #zmiana dtypu z float 32 na float 16
                             device=None #what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [162]:
float_16_tensor=float_32_tensor.type(torch.float32)# zmiana float 16 na float 32
float_16_tensor

tensor([3., 6., 9.])

In [161]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [160]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [163]:
float_16_tensor.dtype

torch.float32

###getting some info from tensors (tensors attributes)


1.    1.TENSORS NOT RIGHT DATATYPE -to get `dtypes`can use tensor.dtype
      2.TENSORS NOT RIGHT SHAPE - to get shape can use tensor.shape
     3.TENSORS NOT ON THE RIGHT DEVICE - to get device use tensor.device





In [164]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0066, 0.8638, 0.5166, 0.4653],
        [0.1775, 0.9911, 0.1721, 0.8404],
        [0.8739, 0.0588, 0.2618, 0.1389]])

In [165]:
#find out details about some tnesor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.0066, 0.8638, 0.5166, 0.4653],
        [0.1775, 0.9911, 0.1721, 0.8404],
        [0.8739, 0.0588, 0.2618, 0.1389]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


In [166]:
jakis_tensor=torch.rand(2,4,3)
jakis_tensor

tensor([[[0.1190, 0.6350, 0.8554],
         [0.0195, 0.1941, 0.7099],
         [0.1905, 0.2714, 0.4021],
         [0.8936, 0.3787, 0.9432]],

        [[0.7126, 0.4698, 0.6792],
         [0.4471, 0.2698, 0.6398],
         [0.1825, 0.3371, 0.0049],
         [0.3610, 0.8129, 0.1159]]])

In [167]:
jakis_tensor.dtype

torch.float32

In [168]:
jakis_tensor_nowy=jakis_tensor.type(torch.float64)
jakis_tensor_nowy

tensor([[[0.1190, 0.6350, 0.8554],
         [0.0195, 0.1941, 0.7099],
         [0.1905, 0.2714, 0.4021],
         [0.8936, 0.3787, 0.9432]],

        [[0.7126, 0.4698, 0.6792],
         [0.4471, 0.2698, 0.6398],
         [0.1825, 0.3371, 0.0049],
         [0.3610, 0.8129, 0.1159]]], dtype=torch.float64)

In [171]:
print(f"data type tego:{jakis_tensor_nowy.dtype}")
print(f"ksztalt tego nowego{jakis_tensor_nowy.shape}")
print(f"na jakim device idzie {jakis_tensor_nowy.device}")

data type tego:torch.float64
ksztalt tego nowegotorch.Size([2, 4, 3])
na jakim device idzie cpu


#MANIPUALTING TENSORS TENSORS OPERATIONS!

In [ ]:
###TENSORS operation include
#Addition
#Subctraction
#Multiplication(element-wise)
#Division
#Matrix multiplication

In [172]:
#crate a tensor
tensor=torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [173]:
tensor * 10

tensor([10, 20, 30])

In [174]:
tensor

tensor([1, 2, 3])

In [175]:
#tensor=tensor*10

In [176]:
tensor

tensor([10, 20, 30])

In [177]:
tensor - 10

tensor([ 0, 10, 20])

In [178]:
tensor


tensor([10, 20, 30])

In [179]:
tensor

tensor([10, 20, 30])

In [180]:
torch.mul(tensor,10)

tensor([100, 200, 300])

In [181]:
torch.add(tensor,10)

tensor([20, 30, 40])

In [ ]:
#MATRIX MULTIPLICATION 2 WAYS:
#ELEMENT-WISE MULTIPLICATION
#MATRIX MULTIPLICATION(dot product)

In [185]:
print(tensor,"*", tensor) # zwykle mnozenie

tensor([10, 20, 30]) * tensor([10, 20, 30])


In [186]:
print(f"Equals:{tensor * tensor}")

Equals:tensor([100, 400, 900])


In [ ]:
#teraz mnozenie prezz marix multiplication

In [187]:
torch.matmul(tensor, tensor) #MATMUL metoda matematyczna pytorcha

tensor(1400)

In [188]:
#matrix multiplication by hand
tensor

tensor([10, 20, 30])

In [190]:
 10 *10 + 20*20+ 30*30 

1400

In [192]:
%%time 
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 520 µs, sys: 0 ns, total: 520 µs
Wall time: 528 µs


In [193]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 720 µs, sys: 0 ns, total: 720 µs
Wall time: 477 µs


tensor(1400)

In [ ]:
#SHAPE ERROR IN MATRIX MULTIPLICATION
#1. THE **INNER DIMENSIONS UST MATCH:
#(3,[2]) @ ([3],2) WONT WORK, ---> @ MNOZENIE, [2][3]--->inner dimensions,MUSZA BYC TAKIE SAME ZEBY ZADZIALALO!
#(2,[3]) @ ([3],2) WILL WORK --->[]MUSZA BYC TAKIE SAME
#(3,[2]) @ ([2],3) WILL WORK --->[]MUSZA BYC TAKIE SAME
#
#2.THE RESULTING MATRIX HAS THE SHAPE OF THE ** OUTER DIMENSIONS:
#(2,3) @ (3,2) --->(2,2)
#(3,2) @ (2,3) ---> (3,3)

In [195]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [196]:
torch.matmul(torch.rand(2,3), torch.rand(3,2)) #MM---> KROTSZA WERSJA OF MATMUL,SKROT MM

tensor([[0.6385, 0.4011],
        [0.9709, 0.6509]])

In [198]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

#Shapes for matrix multiplication

In [199]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])



In [200]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [201]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B).SHAPE

RuntimeError: ignored

In [202]:
#torch.mm(tensor_A,tensor_B).shape

RuntimeError: ignored

In [203]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

TO FIX OUT TENSOR SHAPE ISSUES WE CAN MANIPULATE THE SHAPE OF ONE OF OUR TENSORS USING TRANSPOSE!!!

A TRANSPOSE SWITCHES THE AXES OR DIMENSIONS OF A GIVEN TENSOR

In [205]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [206]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [209]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [210]:
tensor_B.shape

torch.Size([3, 2])

In [211]:
tensor_B.T.shape

torch.Size([2, 3])

In [213]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [214]:
#The matrix multiplication operation works when tensor_B is transposed (T)
print(f"Original shapes: tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape} (SAME SHAPE AS ABOVE), tensor_B.T={tensor_B.T.shape}")
print(f"multiplying:{tensor_A.shape} @ {tensor_B.T.shape}<----- INNER DIMENSIONS MUST MUCH")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2]) (SAME SHAPE AS ABOVE), tensor_B.T=torch.Size([2, 3])
multiplying:torch.Size([3, 2]) @ torch.Size([2, 3])<----- INNER DIMENSIONS MUST MUCH
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
